FROM python:3.9-slim
WORKDIR /app

# Aseguramos instalar las dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiamos el código
COPY . .

# Comando para ejecutar Streamlit
CMD ["streamlit", "run", "frontend/Inicio.py", "--server.port=8501", "--server.address=0.0.0.0"]
